name: Build BeSafe APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip python3-setuptools zip unzip openjdk-11-jdk build-essential libssl-dev libffi-dev libsqlite3-dev
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user buildozer cython

      - name: Add local bin to PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Show Python version
        run: python3 --version

      - name: Build APK (debug)
        run: |
          buildozer -v android debug
        env:
          LD_LIBRARY_PATH: /usr/lib/jvm/java-11-openjdk-amd64/lib

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: be-safe-apk
          path: bin/*.apk
